---

#thought about splitting this into two yml files... but requires a restart of pbs_server
# on the headnode *after* pbs_mom is running on computes... so no.

   - name: create munge key # MUNGE DOESN'T WORK AS INSTALLED FROM THE REPO... 
     command: create-munge-key
     when: submit_host == "yes"

   - name: copy munge key back to management machine
     synchronize:
      mode: pull
      use_ssh_args: yes
      src: /etc/munge/munge.key
      dest: roles/slurm/files/munge.key
     when: submit_host == "yes"

   - name: enable and start munge
     service: name=munge.service enabled=yes state=started
     when: submit_host == "yes"

   - name: ensure build dir exists
     file: path=/root/build/slurm-{{ slurm_version }} state=directory recurse=yes
     when: submit_host == "yes"

   - name: provide slurm source
     synchronize:
      mode: push
      use_ssh_args: yes
      src: files/slurm-{{ slurm_version }}.tar.bz2
      dest: /root/build/slurm-{{ slurm_version }}/
     when: submit_host == "yes"

   - name: rpmbuild slurm
     command: rpmbuild -ta slurm-{{ slurm_version }}.tar.bz2
     args:
       chdir: "/root/build/slurm-{{ slurm_version }}"
       creates: "/root/rpmbuild/RPMS/x86_64/slurm-{{ slurm_version }}-1.el7.centos.x86_64.rpm"
     when: submit_host == "yes"

   - name: install slurm rpms
     yum: 
       name: "{{ item }}"
       state: present
     with_items:
       - "/root/rpmbuild/RPMS/x86_64/slurm-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-devel-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-munge-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-openlava-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-pam_slurm-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-perlapi-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-plugins-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-seff-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-sjobexit-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-sjstat-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-slurmdbd-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-slurmdb-direct-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-sql-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-torque-16.05.4-1.el7.centos.x86_64.rpm"
     when: submit_host == "yes"

   - name: create dir for rpms in /N
     file: path="/N/slurm_rpms/" state=directory
     when: submit_host == "yes"

   - name: copy slurm rpms to /N
     copy:
       remote_src: True
       src: "{{ item }}"
       dest: /N/slurm_rpms/
     with_items:
       - "/root/rpmbuild/RPMS/x86_64/slurm-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-devel-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-munge-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-perlapi-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-plugins-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-sjobexit-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-sjstat-16.05.4-1.el7.centos.x86_64.rpm"
       - "/root/rpmbuild/RPMS/x86_64/slurm-torque-16.05.4-1.el7.centos.x86_64.rpm"
     when: submit_host == "yes"
       #- "/root/rpmbuild/RPMS/x86_64/slurm-seff-16.05.4-1.el7.centos.x86_64.rpm"
       #- "/root/rpmbuild/RPMS/x86_64/slurm-slurmdbd-16.05.4-1.el7.centos.x86_64.rpm"
       #- "/root/rpmbuild/RPMS/x86_64/slurm-slurmdb-direct-16.05.4-1.el7.centos.x86_64.rpm"
       #- "/root/rpmbuild/RPMS/x86_64/slurm-sql-16.05.4-1.el7.centos.x86_64.rpm"
       #- "/root/rpmbuild/RPMS/x86_64/slurm-openlava-16.05.4-1.el7.centos.x86_64.rpm"
       #- "/root/rpmbuild/RPMS/x86_64/slurm-pam_slurm-16.05.4-1.el7.centos.x86_64.rpm"


   - name: install slurm rpms
     yum: 
       name: "{{ item }}"
       state: present
     with_items:
       - "/N/slurm_rpms/slurm-16.05.4-1.el7.centos.x86_64.rpm"
       - "/N/slurm_rpms/slurm-devel-16.05.4-1.el7.centos.x86_64.rpm"
       - "/N/slurm_rpms/slurm-munge-16.05.4-1.el7.centos.x86_64.rpm"
       - "/N/slurm_rpms/slurm-perlapi-16.05.4-1.el7.centos.x86_64.rpm"
       - "/N/slurm_rpms/slurm-plugins-16.05.4-1.el7.centos.x86_64.rpm"
       - "/N/slurm_rpms/slurm-sjobexit-16.05.4-1.el7.centos.x86_64.rpm"
       - "/N/slurm_rpms/slurm-sjstat-16.05.4-1.el7.centos.x86_64.rpm"
       - "/N/slurm_rpms/slurm-torque-16.05.4-1.el7.centos.x86_64.rpm"
     when: submit_host == "no"

   - name: create slurm.conf
     template: src=slurm_conf.j2 dest=/etc/slurm/slurm.conf

   - name: start slurmctld 
     service: name=slurmctld state=restarted enabled=yes
     when: submit_host == "yes"
  
   - name: start slurmd
     service: name=slurmd state=restarted enabled=yes
     when: submit_host == "no"

#   - name: start pbs_server and pbs_sched on submit nodes
#     service: name=pbs_{{ item }} state=started enabled=yes
#     with_items:
#       - "server"
#       - "sched"
#     when: submit_host == "yes"

#   - name: copy mom and client packages to compute nodes
#     synchronize:
#       mode: push
#       use_ssh_args: yes
#       src: files/{{ item }}
#       dest: "/root/{{ item }}"
#     when: submit_host == "no"
#     with_items:
#       - "slurm-package-mom-linux-x86_64.sh"
#       - "slurm-package-clients-linux-x86_64.sh"
#       - "pbs_mom.service"

   - name: copy munge key from submit node
     synchronize:
       mode: push
       src: files/munge.key
       dest: /etc/munge/munge.key
     when: submit_host == "no"
#     with_fileglob:
#       - files/*munge.key

   - name: enable and start munge
     service: name=munge.service enabled=yes state=started
     when: submit_host == "no"

#   - name: install mom package on compute nodes
#     command: "/root/slurm-package-mom-linux-x86_64.sh --install"
#     when: submit_host == "no"
