---

 - name: install scientific apps from XNIT
   yum: name={{ item }} state=present
   with_items:
    - "gromacs" #these need testing for the right package names!
    - "lammps"
    - "nwchem"

- name: build and install Quantum Espresso
  include: build_qe.yml
