---
 
 - name: create the user "grid_user" with a key
   user:
     name: grid_user
     shell: /bin/bash
     generate_ssh_key: yes
     state: present
     createhome: yes
   when: cleanup == "no"

 - name: copy key back to management machine
   synchronize:
     mode: pull
     use_ssh_args: yes
     src: /home/grid_user/.ssh/id_rsa.pub
     dest: roles/grid_user/files/{{ inventory_hostname }}_id_rsa.pub
   when: cleanup == "no"

 - name: copy host key back to management machine
   synchronize:
     mode: pull
     use_ssh_args: yes
     src: /etc/ssh/ssh_host_ecdsa_key.pub
     dest: roles/grid_user/files/{{ inventory_hostname }}_host_key.pub
   when: cleanup == "no"
 
 - name: add mpi module to bashrc
   lineinfile: 
     dest: /home/grid_user/.bashrc 
     state: present
     line: "module load mpi"
 
 - name: edit host key file to contain hostname
   local_action: lineinfile 
                 dest=roles/grid_user/files/{{ inventory_hostname }}_host_key.pub
                 regexp='^(.*)$' 
                 backrefs=yes
                 line='{{ inventory_hostname }} \1'
   when: cleanup == "yes"

 - name: copy ssh keys to all nodes
   authorized_key:
     user: grid_user
     key: "{{ lookup('file','{{ item }}') }} "
   with_fileglob:
     - files/*_id_rsa.pub 
   when: cleanup == "yes"

# will this work?!
 - name: copy host keys to all nodes
   assemble: src=files regexp=_host_key.pub dest=/etc/ssh/ssh_known_hosts remote_src=no
   when: cleanup == "yes"

 - name: provide sample pbs job script
   copy: src=files/node_query.job dest=/home/grid_user/node_query.job owner=grid_user mode=644
   when: (submit_host == "yes" and cleanup == "yes")

 - name: add module load to .bashrc...
   lineinfile: dest=/home/grid_user/.bashrc line="module load mpi" insertafter=EOF state=present owner=grid_user
   when: cleanup == "yes"
