---
 
 - name: create the user "grid_user" with a key
   user:
     name: grid_user
     shell: /bin/bash
     generate_ssh_key: yes
     state: present
     createhome: yes
   when: submit_host == "yes"

 - name: copy key back to management machine
   synchronize:
     mode: pull
     use_ssh_args: yes
     src: /home/grid_user/.ssh/id_rsa.pub
     dest: roles/grid_user/files/{{ inventory_hostname }}id_rsa.pub
   when: submit_host == "yes"

#     dest: ./roles/grid_user_compute/files/{{ inventory_hostname }}id_rsa.pub

 - name: create the user "grid_user" without a key
   user:
     name: grid_user
     shell: /bin/bash
     generate_ssh_key: no
     state: present
     createhome: yes
   when: submit_host == "no"

 - name: copy key from submit node
   authorized_key:
     user: grid_user
     key: "{{ lookup('file','{{ item }}') }} "
   with_fileglob:
     - files/*id_rsa.pub 
   when: submit_host == "no"
# Yes, that is disgusting, but handles multiple submit nodes!
