---

 - set_fact:
     user_name: "{{ item }}"

 - name: authorize ssh keys to submit nodes for {{ user_name }}
   authorized_key:
     user: "{{ user_name }}"
     key: "{{ lookup('file','{}_id_rsa.pub'.format(user_name)) }} "
   when: submit_host == "yes"

 - name: authorize outside ssh key to submit nodes
   authorized_key:
     user: "{{ user_name }}"
     key: "{{ lookup('file','user_keys/{}.pub'.format(user_name)) }} "
   when: submit_host == "yes"
   ignore_errors: yes

 - name: provide sample slurm job script
   copy: src=slurm_example.job dest=/home/{{ user_name }}/slurm_example.job owner={{ user_name }} mode=644
   when: submit_host == "yes"

 - name: provide sample torque job script
   copy: src=torque_example.job dest=/home/{{ user_name }}/torque_example.job owner={{ user_name }} mode=644
   when: submit_host == "yes"

 - name: add module load to .bashrc...
   lineinfile: dest=/home/{{ user_name }}/.bashrc line="module load mpi" insertafter=EOF state=present owner={{ user_name }}
   when: submit_host == "yes"
