---
 
 - name: create the user "grid_user"
   user:
     name: grid_user
     shell: /bin/bash
     generate_ssh_key: yes
     state: present
     createhome: yes

 - name: copy key back to management machine
   synchronize:
    mode: pull
    use_ssh_args: yes
    src: /home/grid_user/.ssh/id_rsa.pub
    dest: ./roles/grid_user_compute/files/{{ inventory_hostname }}id_rsa.pub

