---
 
 - name: install libselinux-python packages
   yum: name=libselinux-python state=present

 - name: set up /etc/hosts
   template: src=hosts.j2 dest=/etc/hosts

 - name: set hostname
   hostname: name={{ inventory_hostname }}

 - name: turn off requiretty for sudo
   lineinfile:
     dest: /etc/sudoers
     regexp: "Defaults    requiretty"
     line:  "Defaults    !requiretty"

 - name: install common packages
   yum: name={{ item }} state=present
   with_items:
     - "boost-devel"    
     - "net-tools"
     - "strace"
     - "python-pip"
     - "vim" 
     - "rsync"
     - "epel-release"
     - "openmpi"     
     - "openmpi-devel"       
#     - "gcc"           
#     - "gcc-c++"       
#     - "gcc-gfortran"  
#     - "openssl-devel" 
#     - "libxml2-devel"  #not installed in heat

 - name: install pexpect from pip
   pip: name=pexpect version=3.3
   when: submit_host == "yes"
