---
 
 - name: install common packages
   yum: name={{ item }} state=latest
   with_items:
     - "vim" 
     - "rsync"
     - "libselinux-python"
     - "gcc"           #torque
     - "gcc-c++"       #torque
     - "gcc-gfortran"  #torque
     - "openssl-devel" #torque
     - "libxml2-devel" #torque
     - "boost-devel"   #torque
#     - "epel-release"
#     - "wget" 
#     - "tcpdump"
#     - "whois" 
#     - "lsof" 
#     - "xinetd"
#     - "net-tools"
#     - "exportfs" 
#     - "firewalld"
#     - "pciutils"
#     - "ntp"
