---

# This version for Jetstream cluster!
# Heat handles *most* of the Torque installation...

   - name: enable and start trqauthd
     service: name=trqauthd.service enabled=yes state=started
     when: submit_host == "yes"

   - name: enable and start trqauthd.service
     service: name=trqauthd.service enabled=yes state=started
     when: submit_host == "yes"

   - name: run qterm just in case
     command: "qterm"
     ignore_errors: yes
     when: submit_host == "yes"

   - name: populate nodes file
     template: src=js_pbs_queue.j2 dest=/var/lib/torque/server_priv/nodes
     when: submit_host == "yes"

#make sure servername is correct

   - name: start pbs_server and pbs_sched on submit nodes
     service: name=pbs_{{ item }} state=started enabled=yes
     with_items:
       - "server"
       - "sched"
     when: submit_host == "yes"

#make sure servername is correct in two places?
   - name: correct $pbsserver
     lineinfile: 
       dest: "/etc/torque/mom/config"
       regexp: '$pbsserver'
       line: "$pbsserver {% for host in groups['submit_nodes'] %}{{host    vars['headnode']['ansible_host'] }}{% endfor %}"
     when: submit_host == "no"

   - name: start pbs_mom on compute nodes
     service: name=pbs_mom state=started enabled=yes
     when: submit_host == "no"
