---

# This version for Jetstream cluster!
# Heat handles *most* of the Torque installation...

# already done in heat...
   - name: enable and start trqauthd
     service: name=trqauthd.service enabled=yes state=started
     when: submit_host == "yes"

   - name: restart trqauthd
     service: name=trqauthd.service enabled=yes state=restarted
     when: submit_host == "yes"

   - name: start pbs_server and pbs_sched on submit nodes
     service: name=pbs_{{ item }} state=started enabled=yes
     with_items:
       - "server"
       - "sched"
     when: submit_host == "yes"

   - name: run qterm
     command: "qterm"
     ignore_errors: yes
     when: submit_host == "yes"

   - name: run initial setup
     expect:
       command: /usr/share/doc/torque-4.2.10/torque.setup root
       responses:
         (?i)do you wish to continue: "y"
     when: submit_host == "yes"

   - name: populate nodes file
     template: src=js_pbs_queue.j2 dest=/var/lib/torque/server_priv/nodes
     when: submit_host == "yes"

   - name: correct $pbsserver
     lineinfile: 
       dest: "/etc/torque/mom/config"
       regexp: '$pbsserver'
       line: "$pbsserver {% for host in groups['submit_nodes'] %}{{hostvars['headnode']['ansible_host'] }}{% endfor %}"
     when: submit_host == "no"

   - name: start pbs_mom on compute nodes
     service: name=pbs_mom state=started enabled=yes
     when: submit_host == "no"
