---
  
  - name: ensure epel-release installed
    yum: name={{ item }} state=present
    with_items:
      - "gcc"           #torque
      - "gcc-c++"       #torque
      - "gcc-gfortran"  #torque
      - "openssl-devel" #torque
      - "libxml2-devel" #torque
      - "boost-devel"   #torque
      - "epel-release" #torque
      - "openmpi"

  - name: install torque server and dependencies
    yum: name={{ item }} state=present
    with_items:
      - "torque"
      - "torque-server"
      - "torque-devel"
      - "torque-scheduler"
      - "torque-libs"
      - "torque-client"
      - "torque-docs"
      - "munge"
      - "munge-libs"
    when: submit_host == "yes"

  - name: install torque mom and dependencies
    yum: name={{ item }} state=present
    with_items:
      - "torque"
      - "torque-mom"
      - "torque-libs"
      - "munge"
      - "munge-libs"
    when: submit_host == "no"


  - name: create torque.conf in /etc/ld.so.conf.d/
    lineinfile: dest=/etc/ld.so.conf.d/torque.conf state=present line='/usr/local/lib' create=yes

  - name: run ldconfig
    command: ldconfig
 
  - name: create munge key
    command: create-munge-key
    when: submit_host == "yes"

# THIS WILL CURRENTLY BREAK WITH MULTIPLE SUBMIT NODES!!!
  - name: copy key back to management machine
    synchronize:
      mode: pull
      use_ssh_args: yes
      src: /etc/munge/munge.key
      dest: roles/torque/files/munge.key
    when: submit_host == "yes"

  - name: copy munge key from submit node
    synchronize:
      mode: push
      src: files/munge.key
      dest: /etc/munge/munge.key
    with_fileglob:
      - files/*munge.key
    when: submit_host == "no"
    
  - name: start and enable munge.service
    service: name=munge.service enabled=yes state=started
 
  - name: start and enable trqauthd.service
    service: name=trqauthd.service enabled=yes state=started
 
  - name: populate nodes file
    template: src=pbs_queue.j2 dest=/var/lib/torque/server_priv/nodes
    when: submit_host == "yes"

#   - name: create a default queue
#     command: torque.setup root
#     args:
#       chdir: "/root/build/torque-{{ torque_version }}"

  - name: start and enable pbs_server
    service: name=pbs_server.service state=started enabled=yes
    when: submit_host == "yes"

  - name: start and enable pbs_mom
    service: name=pbs_mom.service state=started enabled=yes
    when: submit_host == "no"
